language: node_js
node_js: '12'
install: yarn install && yarn install-local-plugins
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn stage; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn build; fi'
deploy:
  skip_cleanup: true
  provider: script
  script: yarn deploy
  on:
    branch: master
